services:
  db-main:
    container_name: db-main
    build: ./database-main
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=main-db_patient_health_record
    volumes:
      - db-main:/var/lib/postgresql/data
    networks:
      - replication-network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U admin -d main-db_patient_health_record"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-slave:
    container_name: db-slave
    build: ./database-slave
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_patient_health_record
    volumes:
      - db-slave:/var/lib/postgresql/data
    networks:
      - replication-network
    depends_on:
      db-main:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U admin"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

networks:
  replication-network:
    driver: bridge

volumes:
  db-main:
    driver: local

  db-slave:
    driver: local
