services:
  db-main:
    container_name: db-main
    build: ./database-main
    ports:
      - 5432:5432
    environment:
      # Main DB credentials
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_patient_health_record
      # Replication settings (used by setup-replication.sh)
      - REPLICATION_USER=repl_user
      - REPLICATION_PASSWORD=your_secure_replication_password
    volumes:
      - db-main:/var/lib/postgresql/data
    networks:
      - replication-network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d db_patient_health_record
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db-slave:
    container_name: db-slave
    build: ./database-slave
    ports:
      - 5433:5432
    environment:
      # Replica DB credentials (must match primary for replication)
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_patient_health_record
      # Replication settings (used by setup-replica.sh)
      - REPLICATION_USER=repl_user
      - REPLICATION_PASSWORD=your_secure_replication_password
    volumes:
      - db-slave:/var/lib/postgresql/data
    networks:
      - replication-network
    depends_on:
      db-main:
        condition: service_healthy
    # Optionally, you can enable healthcheck for the replica as well
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d db_patient_health_record
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ubuntu-service:
    image: ubuntu:latest
    container_name: ubuntu-service
    command:
      [
        "bash",
        "-c",
        "apt-get update && apt-get install -y iputils-ping && tail -f /dev/null",
      ]
    networks:
      - replication-network

networks:
  replication-network:
    driver: bridge

volumes:
  db-main:
    driver: local

  db-slave:
    driver: local
